name: Android CI

on:
  push:
    branches: [ "main", "UI-Frontend_test", "UI-Frontend_test_mit_wallpaper_changer" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: JDK einrichten
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin' 
        cache: 'gradle' 
        
    - name: Gradle Wrapper ausführbar machen
      run: chmod +x ./gradlew

    - name: Lint prüfen
      run: ./gradlew lint

    - name: Mit Gradle bauen
      run: ./gradlew assembleDebug assembleRelease --stacktrace

    - name: Unit-Tests ausführen
      run: ./gradlew testDebugUnitTest --stacktrace

    - name: Build Debug- und Release-APK
      run: ./gradlew assembleDebug assembleRelease --stacktrace

    - name: Debug-APK prüfen
      run: ls -lh app/build/outputs/apk/debug/

    - name: Release-APK prüfen
      run: ls -lh app/build/outputs/apk/release/

    - name: Debug-APK hochladen
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk 
        path: app/build/outputs/apk/debug/app-debug.apk 
        if-no-files-found: error 
    
    - name: Release-APK hochladen
      uses: actions/upload-artifact@v4
      with:
        name: app-release-apk 
        path: app/build/outputs/apk/release/app-release.apk
        if-no-files-found: error
