name: Generate Keystore

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate keystore
        run: |
            keytool -genkeypair \
            -alias my-key-alias \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass my-keystore-pass \
            -keypass my-key-pass \
            -dname "CN=My Name, OU=MyOrg, O=MyCompany, L=City, S=State, C=DE" \
            -keystore keystore.jks
         

      - name: Encode keystore as base64
        run: base64 keystore.jks > keystore.jks.base64

      - name: Show encoded keystore (for secret input)
        run: cat keystore.jks.base64
